BEGIN;
DROP TABLE "core_character";
DROP TABLE "core_character";
ALTER TABLE "cyber_computer_ice" DROP CONSTRAINT computer_id_refs_name_4c65d46f;
ALTER TABLE "cyber_computer_links_to" DROP CONSTRAINT to_computer_id_refs_name_7e84bfe4;
ALTER TABLE "cyber_computer_links_to" DROP CONSTRAINT from_computer_id_refs_name_7e84bfe4;
ALTER TABLE "cyber_access" DROP CONSTRAINT computer_id_refs_name_7ce4a75e;
DROP TABLE "cyber_computer";
DROP TABLE "cyber_computer_ice";
DROP TABLE "cyber_computer_links_to";
DROP TABLE "cyber_access";
DROP TABLE "cyber_ice";
DROP TABLE "cyber_trance";
ALTER TABLE "cyber_cyberfile_container" DROP CONSTRAINT cyberfile_id_refs_id_6e89c2ab;
DROP TABLE "cyber_cyberfile";
DROP TABLE "cyber_cyberfile_container";
DROP TABLE "cyber_picture";
DROP TABLE "cyber_word";
DROP TABLE "cyber_rumor";
DROP TABLE "elog_event";
DROP TABLE "mail_mail";
DROP TABLE "media_factor";
DROP TABLE "media_position";
DROP TABLE "media_subject";
DROP TABLE "media_agent";
ALTER TABLE "media_post_characters" DROP CONSTRAINT post_id_refs_id_4376b201;
ALTER TABLE "media_post_fameItems" DROP CONSTRAINT post_id_refs_id_289e7aa7;
ALTER TABLE "media_post_sinkers" DROP CONSTRAINT post_id_refs_id_4eae10c7;
ALTER TABLE "media_post_swimmers" DROP CONSTRAINT post_id_refs_id_41aa0226;
DROP TABLE "media_post";
DROP TABLE "media_post_characters";
DROP TABLE "media_post_fameItems";
DROP TABLE "media_post_sinkers";
DROP TABLE "media_post_swimmers";
DROP TABLE "media_fameitem";
DROP TABLE "pedia_entry";
DROP TABLE "research_research";
ALTER TABLE "research_tech_prereqs" DROP CONSTRAINT to_tech_id_refs_startCode_4f8bdaa0;
ALTER TABLE "research_tech_prereqs" DROP CONSTRAINT from_tech_id_refs_startCode_4f8bdaa0;
DROP TABLE "research_tech";
DROP TABLE "research_tech_prereqs";
COMMIT;
